name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2.0.0
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v5  # This also runs nix-build.
      with:
        name: srid
