name: "Deploy"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v6
    - uses: cachix/cachix-action@v3  # This also runs nix-build.
      with:
        name: srid
    - name: Generate site
      run: $(nix-build)/bin/rib-sample generate --full
    - name: GitHub Pages Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dest # The folder the action should deploy.
